//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVPMistico.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PVPMistico.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir entrenador.
        /// </summary>
        public static string AddTrainerButtonText {
            get {
                return ResourceManager.GetString("AddTrainerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por usuario.
        /// </summary>
        public static string AddTrainerSearchPlaceholder {
            get {
                return ResourceManager.GetString("AddTrainerSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De acuerdo.
        /// </summary>
        public static string AlertDialogOkButton {
            get {
                return ResourceManager.GetString("AlertDialogOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido añadir a este entrenador.
        /// </summary>
        public static string CannotAddTrainer {
            get {
                return ResourceManager.GetString("CannotAddTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string ConfirmationDialogCancelButton {
            get {
                return ResourceManager.GetString("ConfirmationDialogCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string ConfirmationDialogOkButton {
            get {
                return ResourceManager.GetString("ConfirmationDialogOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nuevo torneo.
        /// </summary>
        public static string CreateLeadearboard {
            get {
                return ResourceManager.GetString("CreateLeadearboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derrota.
        /// </summary>
        public static string Defeat {
            get {
                return ResourceManager.GetString("Defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este correo electrónico está registrado con otro usuario.
        /// </summary>
        public static string EmailAlreadyUsedResponse {
            get {
                return ResourceManager.GetString("EmailAlreadyUsedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo no puede estar vacío..
        /// </summary>
        public static string EmptyEntryError {
            get {
                return ResourceManager.GetString("EmptyEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no puede estar vacío..
        /// </summary>
        public static string EmptyNameError {
            get {
                return ResourceManager.GetString("EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario no puede estar vacio.
        /// </summary>
        public static string EmptyUsernameError {
            get {
                return ResourceManager.GetString("EmptyUsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liga super ball.
        /// </summary>
        public static string GreatLeague {
            get {
                return ResourceManager.GetString("GreatLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir resultado.
        /// </summary>
        public static string InputMatch {
            get {
                return ResourceManager.GetString("InputMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido cargar esta clasificación.
        /// </summary>
        public static string LeaderboardNotFoundToast {
            get {
                return ResourceManager.GetString("LeaderboardNotFoundToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificaciones.
        /// </summary>
        public static string LeaderboardsHeader {
            get {
                return ResourceManager.GetString("LeaderboardsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liga.
        /// </summary>
        public static string LeagueName {
            get {
                return ResourceManager.GetString("LeagueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una liga con este nombre.
        /// </summary>
        public static string LeagueNameAlreadyUsed {
            get {
                return ResourceManager.GetString("LeagueNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la liga.
        /// </summary>
        public static string LeagueNameLabel {
            get {
                return ResourceManager.GetString("LeagueNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de liga.
        /// </summary>
        public static string LeagueTypeLabel {
            get {
                return ResourceManager.GetString("LeagueTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión.
        /// </summary>
        public static string LogInPageTitle {
            get {
                return ResourceManager.GetString("LogInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesión iniciada correctamente.
        /// </summary>
        public static string LogInSuccesfulResponse {
            get {
                return ResourceManager.GetString("LogInSuccesfulResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string LogOutButtonText {
            get {
                return ResourceManager.GetString("LogOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro que quieres cerrar la sesión?.
        /// </summary>
        public static string LogOutConfirmationMessage {
            get {
                return ResourceManager.GetString("LogOutConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrando sesión.
        /// </summary>
        public static string LogOutConfirmationTitle {
            get {
                return ResourceManager.GetString("LogOutConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derrotas.
        /// </summary>
        public static string LosesLabel {
            get {
                return ResourceManager.GetString("LosesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página principal.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liga master ball.
        /// </summary>
        public static string MasterLeague {
            get {
                return ResourceManager.GetString("MasterLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de partidas.
        /// </summary>
        public static string MatchHistory {
            get {
                return ResourceManager.GetString("MatchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de partidas.
        /// </summary>
        public static string MatchHistoryButtonText {
            get {
                return ResourceManager.GetString("MatchHistoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No quedan usuarios registrados por añadir.
        /// </summary>
        public static string NoTrainersLeftToAdd {
            get {
                return ResourceManager.GetString("NoTrainersLeftToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrincante.
        /// </summary>
        public static string Opponent {
            get {
                return ResourceManager.GetString("Opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener entre minimum y maximum carácteres, incluyendo una letra mayúscula, una minúscula y un número..
        /// </summary>
        public static string PasswordFormatInvalidPlaceholder {
            get {
                return ResourceManager.GetString("PasswordFormatInvalidPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta.
        /// </summary>
        public static string PasswordIncorrectResponse {
            get {
                return ResourceManager.GetString("PasswordIncorrectResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos.
        /// </summary>
        public static string PointsLabel {
            get {
                return ResourceManager.GetString("PointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición.
        /// </summary>
        public static string PositionLabel {
            get {
                return ResourceManager.GetString("PositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resgistrarse.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInPageTitle {
            get {
                return ResourceManager.GetString("SignInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario registrado correctamente.
        /// </summary>
        public static string SignInSuccessfulResponse {
            get {
                return ResourceManager.GetString("SignInSuccessfulResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liga ultra ball.
        /// </summary>
        public static string UltraLeague {
            get {
                return ResourceManager.GetString("UltraLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuario ya existe..
        /// </summary>
        public static string UserAlreadyExistsError {
            get {
                return ResourceManager.GetString("UserAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuario ya está registrado.
        /// </summary>
        public static string UserAlreadyRegisteredResponse {
            get {
                return ResourceManager.GetString("UserAlreadyRegisteredResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado a ningún usuario registrado con ese nombre.
        /// </summary>
        public static string UsernameNotFoundResponse {
            get {
                return ResourceManager.GetString("UsernameNotFoundResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no está registrado..
        /// </summary>
        public static string UserNotRegisteredError {
            get {
                return ResourceManager.GetString("UserNotRegisteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victoria.
        /// </summary>
        public static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganador.
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victorias.
        /// </summary>
        public static string WinsLabel {
            get {
                return ResourceManager.GetString("WinsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porfavor inserte un formato de e-mail válido..
        /// </summary>
        public static string WrongEmailFormatError {
            get {
                return ResourceManager.GetString("WrongEmailFormatError", resourceCulture);
            }
        }
    }
}
